### PR TITLE
bug/ISS-185

### PR DESCRIPTION
**Pull request by BonnardValentin**
### Pull Request Description

**Title:** Fix Workspace Synchronization After Agent Initialization

**Description:**

This pull request addresses an issue where the workspace was not being synchronized during the first query after initializing an agent with the `@2501 init --config "XXX"` command. The problem was due to the workspace synchronization logic being conditionally executed only when an agent was not already eligible.

**Changes:**

- Ensures that the workspace is always synchronized after an agent is initialized, regardless of whether the workspace is temporary or not.

**Impact:**

- Users will now experience consistent workspace synchronization after initializing an agent, improving the reliability of the CLI tool.

**Related Issues:**

- Fixes: [ISS-185](https://linear.app/2501ai/issue/ISS-185/workspace-was-not-syncronized-when-using-a-dedicated-configuration)

-> CODING_AGENT & PENTESTER , config_id

### CODE REVIEW

**Review by zhuk-aa — CHANGES_REQUESTED** [review]
do we need to add `skipWarmup` param to `index.ts`?
Screenshot 2024-12-03 at 12 12 43

**Comment by BonnardValentin** [comment]
> do we need to add `skipWarmup` param to `index.ts`? or we don't have it intentionally?

it's intentional, I think it's a good separation between the entity that “manages” the commands and the logic itself
But I can changes it if you want

**Comment by zhuk-aa** [comment]
@BonnardValentin in this case, who sets `skipWarmup` in the first place? If it a cli param?

**Comment by BonnardValentin** [comment]
it seems to me that it's useless, because the only time it's set outside the option is `const` skipWarmup = `!!options.skipWarmup;` in queryCommand

**Comment by BonnardValentin** [comment]
> it seems to me that it's useless, because the only time it's set outside the option is `const` skipWarmup = `!!options.skipWarmup;` in queryCommand

 but to avoid any regressions, I kept it

**Pull request merged**
